fix-up.ts not catching our new directory names
pkgxdev/brewkit pull request #233
Opened 2023-12-19 22:37 UTC by jhheider

this creates broken .pc and .cmake output.

see: https://github.com/pkgxdev/pantry/actions/runs/7267412014/job/19801705304

there still seems to be 18-24 hour lag when a package rebuild is "seen" by pantry CI, even though the CDN is serving the right package, so this will take time to clear up. :/

2023-12-20 14:52 UTC, mxcl requested changes

2023-12-20 14:52 UTC, mxcl commented on lib/porcelain/fix-up.ts
> +          .replaceAll(pkg_prefix.join("+brewing").string, `\${pcfiledir}/${relative_path}`)
use the `config` object’s  `build_install` path.

2023-12-20 14:53 UTC, mxcl commented
Sorry I should have thought of this.

2023-12-20 14:56 UTC, mxcl commented
A fixture would prevent this repeating

2023-12-20 14:58 UTC, jhheider commented on lib/porcelain/fix-up.ts
> +          .replaceAll(pkg_prefix.join("+brewing").string, `\${pcfiledir}/${relative_path}`)
cool. i literally just woke up and realized that `.join()` will add a slash and hoped this wasn't merged. ;)

2023-12-20 16:11 UTC, jhheider commented
> A fixture would prevent this regressing

good point: working new fixture: https://github.com/pkgxdev/brewkit/actions/runs/7277880130/job/19830875019

2023-12-21 07:38 UTC, mxcl approved these changes

2023-12-21 07:38 UTC, merged